name = "Sky FABRICation 2"
author = "MSandro"
version = "1.1.0-ClosedBeta4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c379772b4907166618b1bb10c7aa6f75b852cd062415c81ee6495c77a2a229f9"

[versions]
fabric = "0.13.3"
minecraft = "1.17.1"
