name = "Sky FABRICation 2"
author = "MSandro"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5950275865064823f885a526bc21c27e7299c36987b8cc7f3f276d10df055bca"

[versions]
fabric = "0.14.5"
minecraft = "1.17.1"
