name = "Sky FABRICation 2"
author = "MSandro"
version = "1.0.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cb43fe61d951b2b6996baae08d8f0ee645b74bb8803e0c5c20f36a28a5f85b0"

[versions]
fabric = "0.13.2"
minecraft = "1.17.1"
