name = "Sky FABRICation 2"
author = "MSandro"
version = "1.1.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b7dbb2c8fa6b706b24188d5ad3a80c8c72a0cd02c69da4d9745a4da07ab6fdd"

[versions]
fabric = "0.13.3"
minecraft = "1.17.1"
