name = "Sky FABRICation 2"
pack-format = "packwiz:1.0.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34595de3bf4c72ea751f921bce61b8adeba5b9795549a63729e96af2971a5c96"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
