name = "Sky FABRICation 2"
author = "MSandro"
version = "1.1.2a"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed0d6af28b8bb432b4693cc52351cc6f4a1933d74482b79465f161b08430ca88"

[versions]
fabric = "0.13.3"
minecraft = "1.17.1"
