name = "Sky FABRICation 2"
author = "MSandro"
version = "1.0.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79b60e893ccbb3fa588a4eea7055ad30c760258e4fb629a0ffa10c192370801a"

[versions]
fabric = "0.13.2"
minecraft = "1.17.1"
