name = "Sky FABRICation 2"
pack-format = "packwiz:1.0.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a960a0ffc404fa11efe7be4dd27be277d7d7bc4d39e7e359bf4f9fb809f91e86"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
