name = "Sky FABRICation 2"
author = "MSandro"
version = "1.0.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3753eab44c4c485da4b45c7fd65a5fbc66856b32747fdb3bdd3793421c25de99"

[versions]
fabric = "0.13.2"
minecraft = "1.17.1"
