name = "Sky FABRICation 2"
author = "MSandro"
version = "1.1.3b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b65e902d3af5d5a783e27f5fb76fad20ef0b0c05037b5cc714b5395281ba01eb"

[versions]
fabric = "0.14.6"
minecraft = "1.17.1"
