name = "Sky FABRICation 2"
author = "MSandro"
version = "1.0.5b"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1075ebdef4e83f66a08dcd81701da0c5760190cf0b749d8ce0dcd42d3cbc8773"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
