name = "Sky FABRICation 2"
author = "MSandro"
version = "1.0.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fc2ae23f8549e3237bca6377d96ed2d9457faa5745502bff1c666818bdf2200"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
