name = "Sky FABRICation 2"
author = "MSandro"
version = "1.1.3b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f4e1be5329fae40bdb8d051e4f45c7e86b339371d526fd74356e9797af4cf47"

[versions]
fabric = "0.14.6"
minecraft = "1.17.1"
