name = "Sky FABRICation 2"
author = "MSandro"
version = "1.0.5a"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ff76b21a839ef017c2e108cc6e7e926f064f4f37248be997472b50798cf7bd5"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
