name = "Sky FABRICation 2"
author = "MSandro"
version = "1.1.0-pre1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa2648e8075e02402723779f28de47523679682e467fe51470a7afa6427e5888"

[versions]
fabric = "0.13.3"
minecraft = "1.17.1"
