name = "Sky FABRICation 2"
author = "MSandro"
version = "1.1.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2247231763da34f2af6680cee709801b78f1b6bb9d13ce1886101b8fc489d7ef"

[versions]
fabric = "0.13.3"
minecraft = "1.17.1"
