name = "Sky FABRICation 2"
author = "MSandro"
version = "1.1.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2afb86b4abf8c578d8190c34cfcefd48ed6e725521ea16273ba76da4073e3d63"

[versions]
fabric = "0.13.3"
minecraft = "1.17.1"
