name = "Sky FABRICation 2"
author = "MSandro"
version = "1.0.5b"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ffbc06a031841e412e7248c44841dbdb1ac9829ae30840d8a44e437c451c5ea"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
