name = "Sky FABRICation 2"
author = "MSandro"
version = "1.1.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24168f1b218fa9fb3654f36c64f274f8ea8d78fa8468669e001fe32b6777c99d"

[versions]
fabric = "0.13.3"
minecraft = "1.17.1"
