name = "Sky FABRICation 2"
pack-format = "packwiz:1.0.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc1eedc2d232288dd4346bd0c64487be0705547e90a7e55eb353f2f525ec75b3"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
