name = "Sky FABRICation 2"
author = "MSandro"
version = "1.0.5a"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a2dfd54bb88f6b44f2edf4139226876a096650594724883a079861ee2616d26"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
