name = "Sky FABRICation 2"
author = "MSandro"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c3ea433facd5ea41cf48de031c470ef69266b9c93166994031b479c618a8ca6"

[versions]
fabric = "0.14.5"
minecraft = "1.17.1"
