name = "Sky FABRICation 2"
author = "MSandro"
version = "1.0.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d2476fa03adf4b3738f06165ca761aa8f4babc975ca84aeea5aa897f5782dbe"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
