name = "Sky FABRICation 2"
author = "MSandro"
version = "1.1.3b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2c693a89481252320dfdc67d2e0b3602001d84ee36f037a29c17bc6d076a1d8"

[versions]
fabric = "0.14.6"
minecraft = "1.17.1"
