name = "Sky FABRICation 2"
author = "MSandro"
version = "1.1.3a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1820a2374ec17af75c75cc3453590ca3eb604f0c55a212a410dc342b1c339441"

[versions]
fabric = "0.14.6"
minecraft = "1.17.1"
