name = "Sky FABRICation 2"
author = "MSandro"
version = "1.1.2b"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "516a87a320c3cc0447eff390a7fa106d6184b435e1b29b77686afc55f7e4fe9c"

[versions]
fabric = "0.13.3"
minecraft = "1.17.1"
