name = "Sky FABRICation 2"
author = "MSandro"
version = "1.0.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9f79054d63ba4785a02ed4ae24f7550644a33bde505872868e1c2ae1093bdf6"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
