name = "Sky FABRICation 2"
pack-format = "packwiz:1.0.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d786559243a25c7c1bedbc36b6bb81e0b9e2102e5215015632d7c3fd092a6de1"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
