name = "Sky FABRICation 2"
author = "MSandro"
version = "1.1.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e037b1a83afd595bc3ef3b25bea36de753ad5113621d0db45c849d69d75052c3"

[versions]
fabric = "0.13.3"
minecraft = "1.17.1"
