name = "Sky FABRICation 2"
author = "MSandro"
version = "1.1.3a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a2254ea61a380172d0d14276011d2079bbde1ffa04c58a7066d4aeb489f1326"

[versions]
fabric = "0.14.6"
minecraft = "1.17.1"
