name = "Sky FABRICation 2"
author = "MSandro"
version = "1.0.5a"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07e71d54039af2a18270e4493173a4f56c3e0f3718401b892013beda25dbdf7d"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
