name = "Sky FABRICation 2"
author = "MSandro"
version = "1.1.2b"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1ae01f3d08e2735d8ac3e2023d0cf688a3b6a7d5d358451dabc909ce50a7676"

[versions]
fabric = "0.13.3"
minecraft = "1.17.1"
