name = "Sky FABRICation 2"
author = "MSandro"
version = "1.1.2b"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e90abace9fddc62561e9df9daa136310f15ba3435473470f4157145f237cfca"

[versions]
fabric = "0.13.3"
minecraft = "1.17.1"
