name = "Sky FABRICation 2"
author = "MSandro"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b73f1f63e4645e94b053a89284b63b411c6c86971476c7160d7d47739b6170e3"

[versions]
fabric = "0.14.5"
minecraft = "1.17.1"
