# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				panda = true
				bee = true
				egg = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				llama = true
				mule = true
				bat = true
				husk = true
				hoglin = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				turtle = true
				wither_skeleton = true
				wandering_trader = true
				salmon = true
				piglin_brute = true
				goat = true
				ocelot = true
				item_frame = true
				horse = true
				vindicator = true
				phantom = true
				ender_dragon = true
				evoker = true
				mooshroom = true
				llama_spit = true
				snowball = true
				squid = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				dragon_fireball = true
				copper_golem = true
				chicken = true
				trader_llama = true
				donkey = true
				chest_minecart = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				zombified_piglin = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				endermite = true
				cat = true
				zombie = true
				ender_pearl = true
				guardian = true
				ghast = true
				sheep = true
				fireball = true
				player = true
				potion = true
				trident = true
				wolf = true
				villager = true
				skeleton_horse = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				small_fireball = true
				boat = true
				strider = true
				polar_bear = true
				painting = true
				cave_spider = true
				witch = true
				cod = true
				spider = true

			[light_sources.settings.entities.bewitchment]
				werewolf = true
				ghost = true
				raven = true
				owl = true
				vampire = true
				snake = true
				hellhound = true

			[light_sources.settings.entities.betteranimalsplus]
				deer = true
				feralwolf = true
				songbird = true
				badgerdirt = true
				moose = true
				tarantula = true
				badger = true
				boar = true
				squirrel = true
				brownbear = true
				turkey = true
				butterfly = true
				coyote = true
				pheasant = true
				blackbear = true
				lammergeier = true
				crab = true

			[light_sources.settings.entities.timeinabottle]
				accelerator = true

			[light_sources.settings.entities.outvoted]
				glare = true
				copper_golem = true
				wildfire = true

			[light_sources.settings.entities.golemsgalore]
				obsidian_golem = true
				amethyst_golem = true
				laser_golem = true

			[light_sources.settings.entities.terrarianslimes]
				black_slime = true
				corrupt_slime = true
				yellow_slime = true
				mother_slime = true
				sand_slime = true
				green_slime = true
				pinky = true
				red_slime = true
				umbrella_slime = true
				blue_slime = true
				lava_slime = true
				purple_slime = true
				spiked_ice_slime = true

			[light_sources.settings.entities.botania]
				mana_burst = true
				spark = true

			[light_sources.settings.entities.the_bumblezone]
				honey_slime = true
				beehemoth = true

			[light_sources.settings.entities.goblintraders]
				vein_goblin_trader = true
				goblin_trader = true

			[light_sources.settings.entities.betternether]
				naga_projectile = true
				firefly = true
				hydrogen_jellyfish = true
				skull = true
				jungle_skeleton = true
				naga = true

			[light_sources.settings.entities.the_aether]
				aerbunny = true
				poison_needle = true
				aerwhale = true
				aechor_plant = true
				blue_swet = true
				moa = true

			[light_sources.settings.entities.valley]
				duck = true

			[light_sources.settings.entities.edenring]
				lightning_ray = true

