name = "Alloy Forgery"
filename = "wraith-alloy-forgery-2.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3522/575/wraith-alloy-forgery-2.0.6.jar"
hash-format = "murmur2"
hash = "4216730943"

[update]
[update.curseforge]
file-id = 3522575
project-id = 438718
