name = "AppleSkin"
filename = "appleskin-fabric-mc1.17.1-2.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3626/707/appleskin-fabric-mc1.17.1-2.3.0.jar"
hash-format = "murmur2"
hash = "3756739182"

[update]
[update.curseforge]
file-id = 3626707
project-id = 248787
