name = "AppleSkin"
filename = "appleskin-fabric-mc1.17.1-2.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3686/477/appleskin-fabric-mc1.17.1-2.4.0.jar"
hash-format = "sha1"
hash = "fb27045fb96fa6af7f2fea40d0ca37edaece8548"

[update]
[update.curseforge]
file-id = 3686477
project-id = 248787
