name = "Architectury API (Fabric)"
filename = "architectury-2.10.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3742/408/architectury-2.10.8.jar"
hash-format = "murmur2"
hash = "3449466675"

[update]
[update.curseforge]
file-id = 3742408
project-id = 419697
