name = "Architectury API (Fabric)"
filename = "architectury-2.10.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3632/978/architectury-2.10.5.jar"
hash-format = "murmur2"
hash = "956176542"

[update]
[update.curseforge]
file-id = 3632978
project-id = 419697
