name = "Architectury API (Fabric)"
filename = "architectury-2.10.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3705/900/architectury-2.10.7.jar"
hash-format = "sha1"
hash = "63834ad4cdd3992bf70698c2e5e31e7c3c44b5ad"

[update]
[update.curseforge]
file-id = 3705900
project-id = 419697
