name = "Architectury API (Fabric)"
filename = "architectury-2.10.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3636/547/architectury-2.10.6.jar"
hash-format = "murmur2"
hash = "3017330041"

[update]
[update.curseforge]
file-id = 3636547
project-id = 419697
