name = "Architectury API (Fabric)"
filename = "architectury-2.10.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3631/926/architectury-2.10.4.jar"
hash-format = "murmur2"
hash = "2008006288"

[update]
[update.curseforge]
file-id = 3631926
project-id = 419697
