name = "Artis-Recrafted"
filename = "artis-recrafted-2.1.1+1.17.1-dev.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3654/655/artis-recrafted-2.1.1+1.17.1-dev.jar"
hash-format = "sha1"
hash = "29453f2885b302e7a890f61109c415c260f7ac90"

[update]
[update.curseforge]
file-id = 3654655
project-id = 574404
