name = "Audio Output"
filename = "audiooutput-0.0.4.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3351/318/audiooutput-0.0.4.jar"
hash-format = "murmur2"
hash = "1040364283"

[update]
[update.curseforge]
file-id = 3351318
project-id = 372451
