name = "Awesome Dungeon - Fabric"
filename = "AwesomeDungeonFabric-1.17.1-2.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3631/184/AwesomeDungeonFabric-1.17.1-2.0.5.jar"
hash-format = "murmur2"
hash = "3183445890"

[update]
[update.curseforge]
file-id = 3631184
project-id = 530309
