name = "Awesome Dungeon - Fabric"
filename = "AwesomeDungeonFabric-1.17.1-2.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3605/284/AwesomeDungeonFabric-1.17.1-2.0.4.jar"
hash-format = "murmur2"
hash = "3007530440"

[update]
[update.curseforge]
file-id = 3605284
project-id = 530309
