name = "Awesome Dungeon - Fabric"
filename = "AwesomeDungeonFabric-1.17.1-2.0.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3745/921/AwesomeDungeonFabric-1.17.1-2.0.8.jar"
hash-format = "murmur2"
hash = "1865424664"

[update]
[update.curseforge]
file-id = 3745921
project-id = 530309
