name = "Awoken World (Fabric)"
filename = "awokenworld-2.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3505/145/awokenworld-2.0.0.jar"
hash-format = "murmur2"
hash = "3526166283"

[update]
[update.curseforge]
file-id = 3505145
project-id = 514976
