name = "Balm (Fabric Edition)"
filename = "balm-fabric-1.9.0+0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3539/926/balm-fabric-1.9.0+0.jar"
hash-format = "murmur2"
hash = "4255099038"

[update]
[update.curseforge]
file-id = 3539926
project-id = 500525
