name = "BCLib"
filename = "bclib-0.5.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3567/350/bclib-0.5.6.jar"
hash-format = "murmur2"
hash = "1566470350"

[update]
[update.curseforge]
file-id = 3567350
project-id = 495191
