name = "Beacon Overhaul"
filename = "BeaconOverhaul-1.4.3+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3561/450/BeaconOverhaul-1.4.3+1.17.jar"
hash-format = "murmur2"
hash = "1099508926"

[update]
[update.curseforge]
file-id = 3561450
project-id = 430382
