name = "Bountiful (Fabric)"
filename = "BountifulFabric-2.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3533/402/BountifulFabric-2.0.2.jar"
hash-format = "murmur2"
hash = "2127743232"

[update]
[update.curseforge]
file-id = 3533402
project-id = 521673
