name = "Building Wands"
filename = "BuildingWands_mc1.17.1-2.6.3_release-fabric.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "c89cee38e090e6021d36ed1205c61f41d28b8570"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3929465
project-id = 363392
