name = "Building Wands"
filename = "BuildingWands_mc1.17.1-2.6_beta-fabric.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "d7aa262517eb6af774db3636702b75ee29aa1df6"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3875404
project-id = 363392
