name = "Collective (Fabric)"
filename = "collective-fabric-1.17.x-4.25.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3681/231/collective-fabric-1.17.x-4.25.jar"
hash-format = "murmur2"
hash = "3469676150"

[update]
[update.curseforge]
file-id = 3681231
project-id = 526606
