name = "Collective (Fabric)"
filename = "collective-fabric-1.17.x-4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3636/570/collective-fabric-1.17.x-4.0.jar"
hash-format = "murmur2"
hash = "355176585"

[update]
[update.curseforge]
file-id = 3636570
project-id = 526606
