name = "Collective (Fabric)"
filename = "collective-fabric-1.17.x-4.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3638/953/collective-fabric-1.17.x-4.4.jar"
hash-format = "murmur2"
hash = "3318182484"

[update]
[update.curseforge]
file-id = 3638953
project-id = 526606
