name = "Collective (Fabric)"
filename = "collective-fabric-1.17.x-4.26.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3704/28/collective-fabric-1.17.x-4.26.jar"
hash-format = "sha1"
hash = "e917d9c078f0e776bef7a72991da97eadf22fbde"

[update]
[update.curseforge]
file-id = 3704028
project-id = 526606
