name = "Command Aliases (Fabric)"
filename = "commandaliases-1.17-0.4.2.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3351/95/commandaliases-1.17-0.4.2.jar"
hash-format = "murmur2"
hash = "2280234730"

[update]
[update.curseforge]
file-id = 3351095
project-id = 409389
