name = "Compostable Rotten Flesh (Fabric)"
filename = "compostable-rottenflesh-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3346/466/compostable-rottenflesh-1.0.0.jar"
hash-format = "murmur2"
hash = "3422896038"

[update]
[update.curseforge]
file-id = 3346466
project-id = 452832
