name = "Continuity"
filename = "continuity-1.1.0+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3655/791/continuity-1.1.0+1.17.jar"
hash-format = "murmur2"
hash = "2897897558"

[update]
[update.curseforge]
file-id = 3655791
project-id = 531351
