name = "Dark Enchanting"
filename = "dark-enchanting-0.6.0-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3533/438/dark-enchanting-0.6.0-1.17.1.jar"
hash-format = "murmur2"
hash = "4234456495"

[update]
[update.curseforge]
file-id = 3533438
project-id = 473553
