name = "Diagonal Panes"
filename = "fabric-diagonal-panes-0.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3348/819/fabric-diagonal-panes-0.5.0.jar"
hash-format = "murmur2"
hash = "2137021278"

[update]
[update.curseforge]
file-id = 3348819
project-id = 339575
