name = "Drippy Loading Screen [Fabric]"
filename = "drippyloadingscreen_fabric_1.4.1_MC_1.17-1.17.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3543/990/drippyloadingscreen_fabric_1.4.1_MC_1.17-1.17.1.jar"
hash-format = "murmur2"
hash = "787863194"

[update]
[update.curseforge]
file-id = 3543990
project-id = 515172
