name = "Enchantment Descriptions"
filename = "EnchantmentDescriptions-Fabric-1.17.1-8.17.2.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3578/643/EnchantmentDescriptions-Fabric-1.17.1-8.17.2.jar"
hash-format = "murmur2"
hash = "3222932420"

[update]
[update.curseforge]
file-id = 3578643
project-id = 250419
