name = "Enhanced Block Entities"
filename = "enhancedblockentities-0.5+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3461/725/enhancedblockentities-0.5+1.17.jar"
hash-format = "murmur2"
hash = "2100632846"

[update]
[update.curseforge]
file-id = 3461725
project-id = 452046
