name = "Chisel Refabricated"
filename = "chisel-1.4.5+1.17.x.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3695/146/chisel-1.4.5+1.17.x.jar"
hash-format = "murmur2"
hash = "546301942"

[update]
[update.curseforge]
file-id = 3695146
project-id = 551763
