name = "Fabric Language Scala"
filename = "fabric-language-scala-2.0.0+scala.3.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3488/811/fabric-language-scala-2.0.0+scala.3.0.2.jar"
hash-format = "murmur2"
hash = "3265712106"

[update]
[update.curseforge]
file-id = 3488811
project-id = 309275
