name = "Fabrication"
filename = "fabrication-3.1.3+1.17.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "ba4c0f4c2fdf50ceeae25f8c57987fc11866ac0f"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 4065835
project-id = 414445
