name = "Fabric Language Kotlin"
filename = "fabric-language-kotlin-1.7.2+kotlin.1.6.20.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3735/26/fabric-language-kotlin-1.7.2+kotlin.1.6.20.jar"
hash-format = "murmur2"
hash = "1698938928"

[update]
[update.curseforge]
file-id = 3735026
project-id = 308769
