name = "Chisel Refabricated"
filename = "chisel-1.4.4+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3578/87/chisel-1.4.4+1.17.1.jar"
hash-format = "murmur2"
hash = "3585200806"

[update]
[update.curseforge]
file-id = 3578087
project-id = 551763
