name = "Fabric Language Kotlin"
filename = "fabric-language-kotlin-1.7.3+kotlin.1.6.20.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3751/791/fabric-language-kotlin-1.7.3+kotlin.1.6.20.jar"
hash-format = "murmur2"
hash = "2658851603"

[update]
[update.curseforge]
file-id = 3751791
project-id = 308769
