name = "FancyMenu [Fabric]"
filename = "fancymenu_fabric_2.4.2_MC_1.17-1.17.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3566/123/fabrication-1.17-2.3.0.jar"
hash-format = "sha1"
hash = "62793a25cbeb26e4edd1c8fdd7bae4045a485e99"

[update]
[update.curseforge]
file-id = 3544197
project-id = 416796
