name = "FibLib"
filename = "FibLib-1.2.1+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3665/411/FibLib-1.2.1+1.17.jar"
hash-format = "murmur2"
hash = "3934014674"

[update]
[update.curseforge]
file-id = 3665411
project-id = 582729
