name = "Flan"
filename = "flan-1.17.1-1.7.2.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3658/50/flan-1.17.1-1.7.2.jar"
hash-format = "murmur2"
hash = "80622911"

[update]
[update.curseforge]
file-id = 3658050
project-id = 404578
