name = "Flan"
filename = "flan-1.17.1-1.6.7.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3601/469/flan-1.17.1-1.6.7.jar"
hash-format = "murmur2"
hash = "3650230766"

[update]
[update.curseforge]
file-id = 3601469
project-id = 404578
