name = "Forge Config API Port [Fabric]"
filename = "ForgeConfigAPIPort-v2.0.2-1.17.1-Fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3600/916/ForgeConfigAPIPort-v2.0.2-1.17.1-Fabric.jar"
hash-format = "murmur2"
hash = "619498487"

[update]
[update.curseforge]
file-id = 3600916
project-id = 547434
