name = "Game Phases"
filename = "game-phases-1.1.0-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3613/3/game-phases-1.1.0-1.17.1.jar"
hash-format = "murmur2"
hash = "1993172906"

[update]
[update.curseforge]
file-id = 3613003
project-id = 472839
