name = "Gear Reborn"
filename = "GearReborn-1.17-0.1.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3732/105/GearReborn-1.17-0.1.11.jar"
hash-format = "sha1"
hash = "f61c7cf9672ccddd213271bbbf111b9f0bff160c"

[update]
[update.curseforge]
file-id = 3732105
project-id = 418539
