name = "GeckoLib"
filename = "geckolib-fabric-1.17-3.0.31.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3601/140/geckolib-fabric-1.17-3.0.31.jar"
hash-format = "murmur2"
hash = "2731601697"

[update]
[update.curseforge]
file-id = 3601140
project-id = 388172
