name = "GeckoLib"
filename = "geckolib-fabric-1.17-3.0.32.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3661/791/geckolib-fabric-1.17-3.0.32.jar"
hash-format = "sha1"
hash = "34de63abfa33de9ddfb575a1e7d28cc7610c14c3"

[update]
[update.curseforge]
file-id = 3661791
project-id = 388172
