name = "Go Fish"
filename = "go-fish-1.3.1-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/797/go-fish-1.3.1-1.17.1.jar"
hash-format = "murmur2"
hash = "1959143471"

[update]
[update.curseforge]
file-id = 3542797
project-id = 431135
