name = "Grind Enchantments"
filename = "grind-enchantments-1.6.2+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3745/738/grind-enchantments-1.6.2+1.18.2.jar"
hash-format = "murmur2"
hash = "2605813084"

[update]
[update.curseforge]
file-id = 3745738
project-id = 379680
