name = "Grind Enchantments"
filename = "grind-enchantments-1.6.3+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3763/959/grind-enchantments-1.6.3+1.18.2.jar"
hash-format = "murmur2"
hash = "2102304881"

[update]
[update.curseforge]
file-id = 3763959
project-id = 379680
