name = "Hardcore Questing Mode [FORGE/FABRIC]"
filename = "HQM-1.17.1-5.8.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3571/980/HQM-1.17.1-5.8.1-fabric.jar"
hash-format = "murmur2"
hash = "3878877113"

[update]
[update.curseforge]
file-id = 3571980
project-id = 77027
