name = "Iris Shaders"
filename = "iris-mc1.17.1-1.2.4-build.37.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3770/303/iris-mc1.17.1-1.2.4-build.37.jar"
hash-format = "murmur2"
hash = "3940446417"

[update]
[update.curseforge]
file-id = 3770303
project-id = 455508
