name = "Library Ferret - Fabric"
filename = "LibraryFerret-Fabric-1.17.1-1.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3597/887/LibraryFerret-Fabric-1.17.1-1.0.3.jar"
hash-format = "murmur2"
hash = "3526014916"

[update]
[update.curseforge]
file-id = 3597887
project-id = 532730
