name = "Locki"
filename = "locki-0.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3420/851/locki-0.5.0.jar"
hash-format = "murmur2"
hash = "1680243896"

[update]
[update.curseforge]
file-id = 3420851
project-id = 483059
