name = "LuckPerms"
filename = "LuckPerms-Fabric-5.3.84.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3545/765/LuckPerms-Fabric-5.3.84.jar"
hash-format = "murmur2"
hash = "2232779757"

[update]
[update.curseforge]
file-id = 3545765
project-id = 431733
