name = "Mechanical Dispensers"
filename = "MechanicalDispensers-4.0-1.17-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3777/914/MechanicalDispensers-4.0-1.17-1.17.1.jar"
hash-format = "murmur2"
hash = "2016560669"

[update]
[update.curseforge]
file-id = 3777914
project-id = 517886
