name = "Minecraft Transit Railway"
filename = "MTR-fabric-1.17.1-3.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3763/988/MTR-fabric-1.17.1-3.0.0.jar"
hash-format = "murmur2"
hash = "3679898022"

[update]
[update.curseforge]
file-id = 3763988
project-id = 266707
