name = "Minecraft Transit Railway"
filename = "MTR-1.17.1-3.0.0-beta-8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3558/684/MTR-1.17.1-3.0.0-beta-8.jar"
hash-format = "murmur2"
hash = "1111432664"

[update]
[update.curseforge]
file-id = 3558684
project-id = 266707
