name = "Minecraft Transit Railway"
filename = "MTR-fabric-1.17.1-3.1.9.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "6d86b9fee88293e6444dfe8c84baabdffeb30da2"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 4087707
project-id = 266707
