name = "Mo' Structures (Fabric)"
filename = "mostructures-1.3.0+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3740/421/mostructures-1.3.0+1.17.1.jar"
hash-format = "murmur2"
hash = "93471960"

[update]
[update.curseforge]
file-id = 3740421
project-id = 378266
