name = "Modern Industrialization"
filename = "Modern-Industrialization-0.7.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3717/930/Modern-Industrialization-0.7.5.jar"
hash-format = "murmur2"
hash = "2354703002"

[update]
[update.curseforge]
file-id = 3717930
project-id = 405388
