name = "Mod Menu"
filename = "modmenu-2.0.15.jar"
side = "client"

[download]
hash-format = "sha1"
hash = "fbd99bdf47b4b7936b155b341e5f5a13c943509e"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3850095
project-id = 308702
