name = "Mod Menu"
filename = "modmenu-2.0.16.jar"
side = "client"

[download]
hash-format = "sha1"
hash = "178777290b438475af153a90580d10419f94b626"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 4065489
project-id = 308702
