name = "Space Dimensions (Fabric)"
filename = "agape_space_17-0.4.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3568/357/agape_space_17-0.4.2.jar"
hash-format = "murmur2"
hash = "1925198872"

[update]
[update.curseforge]
file-id = 3568357
project-id = 429841
