name = "More Tooltips"
filename = "MoreTooltips-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3422/939/%5B1.17.1%5D%20MoreTooltips-1.0.2.jar"
hash-format = "sha1"
hash = "3abaa227802c610dc8cea1ed08594f812668d800"

[update]
[update.curseforge]
file-id = 3422939
project-id = 421949
