name = "More Villages Mod"
filename = "morevillagesmod-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3516/666/morevillagesmod-1.1.0.jar"
hash-format = "murmur2"
hash = "1288469329"

[update]
[update.curseforge]
file-id = 3516666
project-id = 523090
