name = "More Tooltips"
filename = "%5B1.17.1%5DMoreTooltips-1.0.3.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3638/621/%5B1.17.1%5DMoreTooltips-1.0.3.jar"
hash-format = "murmur2"
hash = "3487159558"

[update]
[update.curseforge]
file-id = 3638621
project-id = 421949
