name = "Nbt Crafting (Fabric)"
filename = "nbtcrafting-2.1.3+mc1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3707/206/nbtcrafting-2.1.3+mc1.17.1.jar"
hash-format = "murmur2"
hash = "493331184"

[update]
[update.curseforge]
file-id = 3707206
project-id = 314633
