name = "Nbt Crafting (Fabric)"
filename = "nbtcrafting-2.1.0+mc1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3477/207/nbtcrafting-2.1.0+mc1.17.1.jar"
hash-format = "murmur2"
hash = "948944381"

[update]
[update.curseforge]
file-id = 3477207
project-id = 314633
