name = "Not Enough Crashes (Fabric)"
filename = "notenoughcrashes-4.1.4+1.17.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3606/836/notenoughcrashes-4.1.4+1.17.1-fabric.jar"
hash-format = "murmur2"
hash = "609917744"

[update]
[update.curseforge]
file-id = 3606836
project-id = 353890
