name = "Not Enough Crashes (Fabric)"
filename = "notenoughcrashes-4.1.2+1.17.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3537/925/notenoughcrashes-4.1.2+1.17.1-fabric.jar"
hash-format = "murmur2"
hash = "3146016725"

[update]
[update.curseforge]
file-id = 3537925
project-id = 353890
