name = "One Block Fish Farm [Fabric]"
filename = "OneBlockFishFarm-mod-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3504/497/OneBlockFishFarm-mod-1.0.0.jar"
hash-format = "murmur2"
hash = "1804642777"

[update]
[update.curseforge]
file-id = 3504497
project-id = 541266
