name = "Outvoted"
filename = "outvoted-1.5.0-rc.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3554/991/outvoted-1.5.0-rc.1.jar"
hash-format = "murmur2"
hash = "4013098601"

[update]
[update.curseforge]
file-id = 3554991
project-id = 415057
