name = "Paradise Lost - The Aether Reborn"
filename = "paradise-lost-1.6.5.3+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3651/306/paradise-lost-1.6.5.3+1.17.1.jar"
hash-format = "sha1"
hash = "2da60b29ead6f59c9caeb2705c86b1e71aeabafa"

[update]
[update.curseforge]
file-id = 3651306
project-id = 418680
