name = "Pehkui"
filename = "Pehkui-2.6.0+1.14.4-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/709/Pehkui-2.6.0+1.14.4-1.18.jar"
hash-format = "murmur2"
hash = "2050219787"

[update]
[update.curseforge]
file-id = 3542709
project-id = 319596
