name = "Plan | Player Analytics"
filename = "PlanFabric-5.4-dev-build-1575.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3636/575/PlanFabric-5.4-dev-build-1575.jar"
hash-format = "murmur2"
hash = "2882698339"

[update]
[update.curseforge]
file-id = 3636575
project-id = 508727
