name = "Platforms [Fabric]"
filename = "platforms-%5Bfabric%5D-1.17-1.1.1-.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3496/259/platforms-%5Bfabric%5D-1.17-1.1.1-.jar"
hash-format = "murmur2"
hash = "3329544672"

[update]
[update.curseforge]
file-id = 3496259
project-id = 536610
