name = "Platforms [Fabric]"
filename = "platforms-fabric-1.17-1.1.6.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "b0317a006d26140ae004ffc9e82bfa44506b6463"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 4053275
project-id = 536610
