name = "Platforms [Fabric]"
filename = "platforms-[fabric]-1.17-1.1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3765/370/platforms-[fabric]-1.17-1.1.4.jar"
hash-format = "murmur2"
hash = "139173590"

[update]
[update.curseforge]
file-id = 3765370
project-id = 536610
