name = "Platforms Fabric"
filename = "platforms-fabric-1.17-1.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/718/platforms-%5Bfabric%5D-1.17-1.1.2.jar"
hash-format = "sha1"
hash = "dba4e8029dc58ed9b2eb8f7b75459a396c3a37c4"

[update]
[update.curseforge]
file-id = 3672718
project-id = 536610
