name = "Platforms Fabric"
filename = "platforms-fabric-1.17-1.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3749/855/platforms-%5Bfabric%5D-1.17-1.1.3.jar"
hash-format = "murmur2"
hash = "483686637"

[update]
[update.curseforge]
file-id = 3749855
project-id = 536610
