name = "Platforms Fabric"
filename = "platforms-fabric-1.17-1.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/718/platforms-%5Bfabric%5D-1.17-1.1.2.jar"
hash-format = "murmur2"
hash = "3725844726"

[update]
[update.curseforge]
file-id = 3672718
project-id = 536610
