name = "Puzzles Lib [Fabric]"
filename = "PuzzlesLib-v2.0.3-1.17.1-Fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3583/445/PuzzlesLib-v2.0.3-1.17.1-Fabric.jar"
hash-format = "murmur2"
hash = "2557231916"

[update]
[update.curseforge]
file-id = 3583445
project-id = 547429
