name = "ShetiPhianCore Fabric"
filename = "shetiphiancore-fabric-1.17-1.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/711/shetiphiancore-%5Bfabric%5D-1.17-1.1.3.jar"
hash-format = "sha1"
hash = "b9b020743dc7bec19415bd10f6829480e2e9b39d"

[update]
[update.curseforge]
file-id = 3672711
project-id = 536603
