name = "ShetiPhianCore [Fabric]"
filename = "shetiphiancore-[fabric]-1.17-1.1.7.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "1ea6b7d846dfddd3b64d1f9f013234b827e6d36f"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3832656
project-id = 536603
