name = "ShetiPhianCore Fabric"
filename = "shetiphiancore-fabric-1.17-1.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/711/shetiphiancore-%5Bfabric%5D-1.17-1.1.3.jar"
hash-format = "murmur2"
hash = "717434982"

[update]
[update.curseforge]
file-id = 3672711
project-id = 536603
