name = "ShetiPhianCore Fabric"
filename = "shetiphiancore-fabric-1.17-1.1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3738/118/shetiphiancore-%5Bfabric%5D-1.17-1.1.4.jar"
hash-format = "murmur2"
hash = "3965896812"

[update]
[update.curseforge]
file-id = 3738118
project-id = 536603
