name = "ShetiPhianCore Fabric"
filename = "shetiphiancore-fabric-1.17-1.1.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3749/189/shetiphiancore-%5Bfabric%5D-1.17-1.1.5.jar"
hash-format = "murmur2"
hash = "836750928"

[update]
[update.curseforge]
file-id = 3749189
project-id = 536603
