name = "ShetiPhianCore [Fabric]"
filename = "shetiphiancore-%5Bfabric%5D-1.17-1.1.1-.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3496/251/shetiphiancore-%5Bfabric%5D-1.17-1.1.1-.jar"
hash-format = "murmur2"
hash = "1129174602"

[update]
[update.curseforge]
file-id = 3496251
project-id = 536603
