name = "ShetiPhianCore [Fabric]"
filename = "shetiphiancore-fabric-1.17-1.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3648/775/shetiphiancore-%5bfabric%5d-1.17-1.1.2.jar"
hash-format = "murmur2"
hash = "1756728280"

[update]
[update.curseforge]
file-id = 3648775
project-id = 536603
