name = "ShetiPhianCore [Fabric]"
filename = "shetiphiancore-fabric-1.17-1.1.12.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "e048036ff1c9b17e352de5c2afe6dcafb7aaad65"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 4085839
project-id = 536603
