name = "Shut Up Console"
filename = "shutupconsole-1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3009/753/shutupconsole-1.1.jar"
hash-format = "murmur2"
hash = "1506437380"

[update]
[update.curseforge]
file-id = 3009753
project-id = 396776
