name = "Simple Teleporters (Fabric)"
filename = "simpleteleporters-2.3.0+fabric-mc1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/221/simpleteleporters-2.3.0+fabric-mc1.17.jar"
hash-format = "murmur2"
hash = "3374857278"

[update]
[update.curseforge]
file-id = 3575221
project-id = 334011
