name = "'Slight' Gui Modifications"
filename = "slight-gui-modifications-2.0.3.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3630/10/slight-gui-modifications-2.0.3.jar"
hash-format = "murmur2"
hash = "3394124502"

[update]
[update.curseforge]
file-id = 3630010
project-id = 380393
