name = "Sodium Extra"
filename = "sodium-extra-mc1.17.1-0.4.3.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3733/68/sodium-extra-mc1.17.1-0.4.3.jar"
hash-format = "murmur2"
hash = "3546259998"

[update]
[update.curseforge]
file-id = 3733068
project-id = 447673
