name = "Styled Chat"
filename = "styled-chat-1.2.0.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3495/245/styled-chat-1.2.0.jar"
hash-format = "murmur2"
hash = "3752107710"

[update]
[update.curseforge]
file-id = 3495245
project-id = 493348
