name = "Sync (Fabric)"
filename = "sync-mc1.17.1-3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3580/638/sync-mc1.17.1-3.1.jar"
hash-format = "murmur2"
hash = "2675726385"

[update]
[update.curseforge]
file-id = 3580638
project-id = 515365
