name = "Textile Backup"
filename = "textile_backup-2.4.0-1.17.jar"
side = "server"

[download]
hash-format = "sha1"
hash = "8e52f25dfae59e4f0049173a774e8f5787268cb5"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3844789
project-id = 359893
