name = "The Big Bench Theory"
filename = "big-bench-theory-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3595/771/big-bench-theory-1.1.0.jar"
hash-format = "murmur2"
hash = "3967179432"

[update]
[update.curseforge]
file-id = 3595771
project-id = 437321
