name = "Trading Post [Fabric]"
filename = "TradingPost-v2.0.0-1.17.1-Fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3527/528/TradingPost-v2.0.0-1.17.1-Fabric.jar"
hash-format = "murmur2"
hash = "975666469"

[update]
[update.curseforge]
file-id = 3527528
project-id = 547472
