name = "Trap Expansion  (Fabric)"
filename = "trapexpansion-1.3.3+fabric-mc1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3482/13/trapexpansion-1.3.3+fabric-mc1.17.jar"
hash-format = "murmur2"
hash = "3427549451"

[update]
[update.curseforge]
file-id = 3482013
project-id = 334018
