name = "ValleyCraft"
filename = "valley-craft-2.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/371/valley-craft-2.0.3.jar"
hash-format = "murmur2"
hash = "3395201053"

[update]
[update.curseforge]
file-id = 3575371
project-id = 527942
