name = "WTHIT"
filename = "wthit-fabric-3.11.3.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "28392f51ebede31603f257d9264e0eb5a1b66386"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3831607
project-id = 440979
