name = "Xaero's World Map"
filename = "XaerosWorldMap_1.20.4.1_Fabric_1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3687/3/XaerosWorldMap_1.20.4.1_Fabric_1.17.1.jar"
hash-format = "murmur2"
hash = "2670069581"

[update]
[update.curseforge]
file-id = 3687003
project-id = 317780
