name = "Xaero's Minimap"
filename = "Xaeros_Minimap_22.5.0_Fabric_1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3738/196/Xaeros_Minimap_22.5.0_Fabric_1.17.1.jar"
hash-format = "murmur2"
hash = "364782251"

[update]
[update.curseforge]
file-id = 3738196
project-id = 263420
