name = "Xaero's World Map"
filename = "XaerosWorldMap_1.20.6_Fabric_1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3732/797/XaerosWorldMap_1.20.6_Fabric_1.17.1.jar"
hash-format = "murmur2"
hash = "5835185"

[update]
[update.curseforge]
file-id = 3732797
project-id = 317780
