name = "Xaero's Minimap"
filename = "Xaeros_Minimap_22.3.1.1_Fabric_1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3686/994/Xaeros_Minimap_22.3.1.1_Fabric_1.17.1.jar"
hash-format = "murmur2"
hash = "2106979248"

[update]
[update.curseforge]
file-id = 3686994
project-id = 263420
