name = "Xaero's World Map"
filename = "XaerosWorldMap_1.20.5_Fabric_1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3712/767/XaerosWorldMap_1.20.5_Fabric_1.17.1.jar"
hash-format = "sha1"
hash = "f78eac9adc20239ce52481041c1567fe86983ca3"

[update]
[update.curseforge]
file-id = 3712767
project-id = 317780
