name = "Xaero's World Map"
filename = "XaerosWorldMap_1.20.7_Fabric_1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3761/740/XaerosWorldMap_1.20.7_Fabric_1.17.1.jar"
hash-format = "murmur2"
hash = "145213157"

[update]
[update.curseforge]
file-id = 3761740
project-id = 317780
