name = "Xaero's World Map"
filename = "XaerosWorldMap_1.20.1_Fabric_1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3626/667/XaerosWorldMap_1.20.1_Fabric_1.17.1.jar"
hash-format = "murmur2"
hash = "765117815"

[update]
[update.curseforge]
file-id = 3626667
project-id = 317780
