name = "Xaero's Minimap"
filename = "Xaeros_Minimap_22.6.1_Fabric_1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3761/735/Xaeros_Minimap_22.6.1_Fabric_1.17.1.jar"
hash-format = "murmur2"
hash = "3151645159"

[update]
[update.curseforge]
file-id = 3761735
project-id = 263420
