name = "Xaero's World Map"
filename = "XaerosWorldMap_1.19.1_Fabric_1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3599/514/XaerosWorldMap_1.19.1_Fabric_1.17.1.jar"
hash-format = "murmur2"
hash = "3816621495"

[update]
[update.curseforge]
file-id = 3599514
project-id = 317780
